package com.youtubevoice.app.dpi

/**
 * Named ByeDPI command-line presets. Auto-tune tries them on-device until HTTPS to YouTube works.
 *
 * Order matters: googleapis + googlevideo-focused strategies first (what usually fails on RU DPI).
 */
data class DpiPreset(
    val id: String,
    val title: String,
    val description: String,
    val args: List<String>,
)

object DpiPresets {
    private fun sock(vararg extra: String): List<String> = buildList {
        add("ciadpi")
        add("--ip"); add("127.0.0.1")
        add("--port"); add(DpiSettingsStore.PROXY_PORT.toString())
        addAll(extra.toList())
    }

    /** Default group that retries on TORST, then a host-scoped always-on group. */
    private fun dualHost(
        defaultArgs: List<String>,
        hosts: String,
        hostArgs: List<String>,
    ): List<String> = sock(
        *defaultArgs.toTypedArray(),
        "--hosts", ":$hosts",
        *hostArgs.toTypedArray(),
        "--auto=none",
    )

    val ALL: List<DpiPreset> = listOf(
        // --- Community-proven (ByeDPIAndroid / 2025–2026) — tried first ---
        DpiPreset(
            id = "community_oob_hosts_yt",
            title = "Community OOB+hosts YT",
            description = "-H youtube/googleapis -n google -o1 -An",
            args = sock(
                "--hosts", ":googlevideo.com youtube.com youtu.be ytimg.com ggpht.com gvt1.com googleapis.com youtubei.googleapis.com google.com",
                "--fake-sni", "www.google.com",
                "--oob", "1",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "community_s0_o1_chain",
            title = "Community s0/o1 chain",
            description = "-Kt,h -s0 -o1 -Ar -o1 -At -f-1 -r1+s -As -An",
            args = sock(
                "--proto", "tls,http",
                "--split", "0",
                "--oob", "1",
                "--auto=redirect",
                "--oob", "1",
                "--auto=torst",
                "--fake", "-1",
                "--tlsrec", "1+s",
                "--auto=ssl_err",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "community_s1_o1_fake",
            title = "Community s1/o1 fake",
            description = "-s1 -o1 -Ar -o1 -At -f-1 -r1+s -As",
            args = sock(
                "--split", "1",
                "--oob", "1",
                "--auto=redirect",
                "--oob", "1",
                "--auto=torst",
                "--fake", "-1",
                "--tlsrec", "1+s",
                "--auto=ssl_err",
            ),
        ),
        DpiPreset(
            id = "community_oob_fake_ttl6",
            title = "Community OOB+fake ttl6",
            description = "hosts YT -n google -o1 -f-1 -ttl 6",
            args = sock(
                "--hosts", ":googlevideo.com youtube.com youtu.be ytimg.com ggpht.com googleapis.com youtubei.googleapis.com",
                "--fake-sni", "www.google.com",
                "--oob", "1",
                "--auto=none",
                "--fake", "-1",
                "--auto=redirect,ssl_err",
                "--oob", "0+sm",
                "--auto=torst",
                "--tlsrec", "1+s",
                "--fake", "-1",
                "--ttl", "6",
                "--proto", "tls",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "community_disorder_torst",
            title = "Community disorder torst",
            description = "--disorder 1 --auto=torst",
            args = sock(
                "--disorder", "1",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "community_split_oob_disorder",
            title = "Community split+oob+d",
            description = "--split 1 --oob 1 --disorder 1",
            args = sock(
                "--split", "1",
                "--oob", "1",
                "--disorder", "1",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "community_gv_oob_only",
            title = "Community GV oob only",
            description = "-H:googlevideo.com -o1 -An (+googleapis)",
            args = sock(
                "--hosts", ":googlevideo.com googleapis.com youtubei.googleapis.com",
                "--oob", "1",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "community_q1s_hosts_gv",
            title = "Community q1+s hosts GV",
            description = "-n google -q1+s -O1 -s25+s -t5 -H GV",
            args = sock(
                "--hosts", ":googlevideo.com googleapis.com youtubei.googleapis.com youtube.com",
                "--fake-sni", "www.google.com",
                "--disoob", "1+s",
                "--fake-offset", "1",
                "--split", "25+s",
                "--ttl", "5",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "community_multisplit_ladder",
            title = "Community multi ladder",
            description = "d1/s0+s … s30+s без auto",
            args = sock(
                "--proto", "tls,http",
                "--disorder", "1",
                "--split", "0+s",
                "--disorder", "3+s",
                "--split", "6+s",
                "--disorder", "9+s",
                "--split", "12+s",
                "--disorder", "15+s",
                "--split", "20+s",
                "--disorder", "25+s",
                "--split", "30+s",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "community_udp_then_tls",
            title = "Community UDP+TLS chain",
            description = "-Ku -a3 -An затем TLS chain",
            args = sock(
                "--udp-fake", "3",
                "--auto=none",
                "--proto", "tls,http",
                "--split", "0",
                "--oob", "1",
                "--auto=redirect",
                "--oob", "1",
                "--auto=torst",
                "--fake", "-1",
                "--tlsrec", "1+s",
                "--auto=ssl_err",
                "--auto=none",
            ),
        ),
        // --- ByeDPI 17.3: fake-sni / fake-tls-mod / ssl_err / mid-SNI ---
        DpiPreset(
            id = "v17_zapret_fake_tlsmod",
            title = "v17 Zapret fake+tlsmod",
            description = "fake-data Google + fake-tls-mod=rand + split",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--fake-tls-mod", "rand",
                "--ttl", "3",
                "--split", "1",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "v17_fake_sni_sslerr",
            title = "v17 fake-sni ssl_err",
            description = "При SSL error — fake Google SNI",
            args = sock(
                "--disorder", "1",
                "--timeout", "3",
                "--auto=ssl_err",
                "--fake", "-1",
                "--fake-sni", "www.google.com",
                "--fake-tls-mod", "rand",
                "--ttl", "3",
                "--split", "1",
            ),
        ),
        DpiPreset(
            id = "v17_split_mid_sni",
            title = "v17 split mid-SNI",
            description = "split 0+sm — разрез середины SNI",
            args = sock(
                "--split", "0+sm",
                "--disorder", "1",
                "--fake", "-1",
                "--fake-sni", "www.google.com",
                "--ttl", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "v17_zapret_multisplit_sni",
            title = "v17 Zapret multi+sni",
            description = "fake Google bin + mid SNI + disorder",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--fake-tls-mod", "rand",
                "--ttl", "3",
                "--split", "1",
                "--split", "0+sm",
                "--disorder", "1",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "v17_dual_api_gv",
            title = "v17 API soft / GV ladder",
            description = "API: fake bin; googlevideo: SNI ladder",
            args = dualHost(
                defaultArgs = listOf(
                    "--proto", "tls,http",
                    "--fake", "-1",
                    "--fake-sni", "www.google.com",
                    "--fake-tls-mod", "rand",
                    "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                    "--ttl", "3",
                    "--split", "1",
                    "--auto=none",
                ),
                hosts = "googlevideo.com",
                hostArgs = listOf(
                    "--disorder", "1",
                    "--disorder", "3+s",
                    "--split", "6+s",
                    "--disorder", "9+s",
                    "--split", "12+s",
                    "--tlsrec", "1+s",
                ),
            ),
        ),
        DpiPreset(
            id = "v17_md5_fake_data",
            title = "v17 md5sig + fake bin",
            description = "md5sig с Zapret ClientHello",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--md5sig",
                "--split", "1",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "v17_fake_orig_mod",
            title = "v17 fake-tls-mod=orig",
            description = "Фейк = модифицированный оригинал ClientHello",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-tls-mod", "orig",
                "--fake-sni", "www.google.com",
                "--ttl", "3",
                "--split", "1",
                "--disorder", "1",
                "--auto=none",
            ),
        ),
        // --- Zapret ALT11 / Flowseal equivalents (fake TLS ClientHello 681B) ---
        DpiPreset(
            id = "zapret_fake_tls_google",
            title = "Zapret fake TLS (Google)",
            description = "Как ALT11: fake ClientHello www.google.com",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "3",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_multisplit",
            title = "Zapret fake+split",
            description = "fake TLS + split 1 + disorder (аналог fake,multisplit)",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "3",
                "--split", "1",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_split_md5",
            title = "Zapret fake+md5sig",
            description = "fake TLS Google + MD5SIG + split",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--md5sig",
                "--split", "1",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_ttl1",
            title = "Zapret fake TTL1",
            description = "Очень низкий TTL фейка (как autottl)",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "1",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_ttl5_ipopt",
            title = "Zapret fake TTL5",
            description = "fake TLS + TTL5",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "5",
                "--split", "1",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_hosts_yt",
            title = "Zapret fake (YT hosts)",
            description = "fake TLS только для youtube/googleapis/googlevideo",
            args = sock(
                "--hosts",
                ":googlevideo.com youtubei.googleapis.com youtube.com ytimg.com ggpht.com googlevideo.com",
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "3",
                "--split", "1",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_max_ru",
            title = "Zapret fake TLS (max.ru)",
            description = "Альтернативный fake ClientHello max.ru",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_MAX_RU,
                "--ttl", "3",
                "--split", "1",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_oob25",
            title = "Zapret fake + OOB 25+s",
            description = "fake TLS Google + oob в длинном SNI",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "3",
                "--oob", "1",
                "--oob", "25+s",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_delay",
            title = "Zapret fake + delay",
            description = "fake TLS с задержкой между кусками",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "3",
                "--split", "1",
                "--disorder", "1",
                "--delay", "10",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_dual_gv",
            title = "Zapret dual (GV hard)",
            description = "API: fake Google; googlevideo: fake+oob25",
            args = dualHost(
                defaultArgs = listOf(
                    "--proto", "tls,http",
                    "--fake", "-1",
                    "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                    "--ttl", "3",
                    "--split", "1",
                    "--timeout", "3",
                    "--auto=none",
                ),
                hosts = "googlevideo.com",
                hostArgs = listOf(
                    "--fake", "-1",
                    "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                    "--ttl", "3",
                    "--disorder", "1",
                    "--oob", "25+s",
                    "--split", "1",
                ),
            ),
        ),
        DpiPreset(
            id = "bchecker_fake_sni",
            title = "B-Checker fake SNI",
            description = "Рекомендация byedpi#372: fake -1 + sni google",
            args = sock(
                "--proto", "http,tls",
                "--fake", "-1",
                "--fake-sni", "www.google.com",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "bchecker_fake_sni_split",
            title = "B-Checker fake+split",
            description = "fake SNI google + split/disorder",
            args = sock(
                "--proto", "http,tls",
                "--fake", "-1",
                "--fake-sni", "www.google.com",
                "--split", "1",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_ttl2",
            title = "Zapret fake TTL2",
            description = "fake Google ClientHello, TTL=2",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "2",
                "--split", "1",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_ttl4",
            title = "Zapret fake TTL4",
            description = "fake Google ClientHello, TTL=4",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "4",
                "--split", "1",
                "--disorder", "1",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_ttl6",
            title = "Zapret fake TTL6",
            description = "fake Google ClientHello, TTL=6",
            args = sock(
                "--proto", "tls,http",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "6",
                "--split", "1",
                "--disorder", "1",
                "--auto=none",
            ),
        ),
        DpiPreset(
            id = "zapret_fake_ttl8_drop_sack",
            title = "Zapret fake+drop-sack",
            description = "fake Google + drop-sack",
            args = sock(
                "--proto", "tls,http",
                "--drop-sack",
                "--fake", "-1",
                "--fake-data", DpiFakeAssets.PLACEHOLDER_GOOGLE,
                "--ttl", "4",
                "--split", "1",
                "--auto=none",
            ),
        ),
        // --- Combos targeting googleapis (short SNI) + googlevideo (long SNI) ---
        DpiPreset(
            id = "api_oob_gv_ladder",
            title = "API OOB / GV ladder",
            description = "googleapis: oob+fake; googlevideo: лестница split",
            args = dualHost(
                defaultArgs = listOf(
                    "--oob", "1",
                    "--oob", "3+s",
                    "--disorder", "1",
                    "--timeout", "3",
                    "--auto=torst",
                    "--fake", "-1",
                    "--ttl", "6",
                ),
                hosts = "googlevideo.com",
                hostArgs = listOf(
                    "--disorder", "1",
                    "--disorder", "3+s",
                    "--split", "6+s",
                    "--disorder", "9+s",
                    "--split", "12+s",
                    "--tlsrec", "1+s",
                ),
            ),
        ),
        DpiPreset(
            id = "api_fake_md5_gv_oob25",
            title = "API md5 / GV oob25",
            description = "googleapis: fake+md5sig; googlevideo: d1+o25+s",
            args = dualHost(
                defaultArgs = listOf(
                    "--fake", "-1",
                    "--md5sig",
                    "--disorder", "1",
                    "--timeout", "3",
                    "--auto=torst",
                ),
                hosts = "googlevideo.com",
                hostArgs = listOf(
                    "--disorder", "1",
                    "--oob", "25+s",
                ),
            ),
        ),
        DpiPreset(
            id = "api_split1_gv_multisplit",
            title = "API split1 / GV multi",
            description = "googleapis: s1+d1; googlevideo: multi split SNI",
            args = dualHost(
                defaultArgs = listOf(
                    "--split", "1",
                    "--disorder", "1",
                    "--timeout", "3",
                    "--auto=torst",
                    "--tlsrec", "1+s",
                    "--fake", "-1",
                    "--ttl", "5",
                ),
                hosts = "googlevideo.com",
                hostArgs = listOf(
                    "--disorder", "1",
                    "--disorder", "3+s",
                    "--split", "6+s",
                    "--disorder", "9+s",
                    "--split", "12+s",
                    "--disorder", "15+s",
                    "--tlsrec", "1+s",
                ),
            ),
        ),
        DpiPreset(
            id = "hosts_googleapis_soft",
            title = "googleapis soft host",
            description = "Отдельная мягкая группа только для googleapis",
            args = dualHost(
                defaultArgs = listOf(
                    "--disorder", "1",
                    "--oob", "25+s",
                    "--timeout", "3",
                    "--auto=torst",
                ),
                hosts = "googleapis.com",
                hostArgs = listOf(
                    "--split", "1",
                    "--oob", "1",
                    "--oob", "2+s",
                    "--fake", "-1",
                    "--ttl", "6",
                    "--disorder", "1",
                    "--tlsrec", "1+s",
                ),
            ),
        ),
        DpiPreset(
            id = "hosts_googleapis_md5",
            title = "googleapis md5 host",
            description = "googleapis через fake+md5sig, остальное d1+o25",
            args = dualHost(
                defaultArgs = listOf(
                    "--disorder", "1",
                    "--oob", "25+s",
                    "--timeout", "3",
                    "--auto=torst",
                ),
                hosts = "googleapis.com",
                hostArgs = listOf(
                    "--fake", "-1",
                    "--md5sig",
                    "--disorder", "1",
                    "--split", "1",
                ),
            ),
        ),
        // --- 2025/2026 community strategies that specifically help googlevideo ---
        DpiPreset(
            id = "d1_o25s",
            title = "Disorder + OOB 25+s",
            description = "Частый рабочий вариант для YT: -d1 -o25+s",
            args = sock(
                "--disorder", "1",
                "--oob", "25+s",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "d1_o23s",
            title = "Disorder + OOB 23+s",
            description = "OOB в длинном SNI (23+s)",
            args = sock(
                "--disorder", "1",
                "--oob", "23+s",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "d1_o28s",
            title = "Disorder + OOB 28+s",
            description = "OOB глубже в SNI (28+s)",
            args = sock(
                "--disorder", "1",
                "--oob", "28+s",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "o1_o25s",
            title = "OOB 1 + OOB 25+s",
            description = "Двойной OOB: начало CH + зона SNI",
            args = sock(
                "--oob", "1",
                "--oob", "25+s",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "d1_r25s",
            title = "Disorder + tlsrec 25+s",
            description = "TLS record deep split в SNI",
            args = sock(
                "--disorder", "1",
                "--tlsrec", "25+s",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "d1_r23s",
            title = "Disorder + tlsrec 23+s",
            description = "TLS record на offset 23+s",
            args = sock(
                "--disorder", "1",
                "--tlsrec", "23+s",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "s1_q1",
            title = "Split + disoob",
            description = "-s1 -q1 — split и reverse OOB",
            args = sock(
                "--split", "1",
                "--disoob", "1",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "s1_d3s_r1s_fake",
            title = "Split/disorder/tlsrec/fake",
            description = "Комбо из свежих гайдов по YT",
            args = sock(
                "--split", "1",
                "--disorder", "3+s",
                "--tlsrec", "1+s",
                "--fake", "-1",
                "--ttl", "3",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "fake_md5sig",
            title = "Fake + MD5SIG",
            description = "Linux: fake с TCP MD5 Signature",
            args = sock(
                "--fake", "-1",
                "--md5sig",
                "--timeout", "3",
                "--auto=torst",
                "--disorder", "1",
            ),
        ),
        DpiPreset(
            id = "fake_ttl3_sni",
            title = "Fake TTL3 + SNI",
            description = "Низкий TTL фейка + google SNI",
            args = sock(
                "--fake", "-1",
                "--ttl", "3",
                "--fake-sni", "www.google.com",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "fake_ttl4_ipopt",
            title = "Fake TTL4",
            description = "Fake TTL4 + SNI google",
            args = sock(
                "--fake", "-1",
                "--ttl", "4",
                "--fake-sni", "www.google.com",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "disoob_sni_fake",
            title = "Disoob SNI + fake",
            description = "disoob в SNI и fake offset",
            args = sock(
                "--disoob", "1+s",
                "--fake", "-1",
                "--fake-offset", "1",
                "--ttl", "5",
                "--fake-sni", "www.google.com",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "s25s_q1s_gv",
            title = "Split 25+s (googlevideo)",
            description = "Специально под googlevideo: -q1+s -s25+s -t5",
            args = dualHost(
                defaultArgs = listOf(
                    "--disorder", "1",
                    "--oob", "1",
                    "--timeout", "3",
                    "--auto=torst",
                    "--fake", "-1",
                    "--ttl", "6",
                ),
                hosts = "googlevideo.com",
                hostArgs = listOf(
                    "--disoob", "1+s",
                    "--fake-offset", "1",
                    "--split", "25+s",
                    "--ttl", "5",
                    "--fake-sni", "www.google.com",
                    "--fake", "-1",
                ),
            ),
        ),
        DpiPreset(
            id = "hosts_api_soft_gv_oob",
            title = "API мягко / GV OOB",
            description = "googleapis: oob+fake; googlevideo: d1+o25+s",
            args = dualHost(
                defaultArgs = listOf(
                    "--oob", "1",
                    "--oob", "3+s",
                    "--timeout", "3",
                    "--auto=torst",
                    "--fake", "-1",
                    "--ttl", "6",
                    "--disorder", "1",
                ),
                hosts = "googlevideo.com",
                hostArgs = listOf(
                    "--disorder", "1",
                    "--oob", "25+s",
                    "--fake", "-1",
                    "--ttl", "3",
                    "--fake-sni", "www.google.com",
                ),
            ),
        ),
        DpiPreset(
            id = "hosts_api_split_gv_disoob",
            title = "API split / GV disoob",
            description = "Разные стратегии: API split, медиа disoob",
            args = dualHost(
                defaultArgs = listOf(
                    "--split", "1",
                    "--disorder", "1",
                    "--timeout", "3",
                    "--auto=torst",
                    "--tlsrec", "1+s",
                    "--fake", "-1",
                    "--ttl", "5",
                ),
                hosts = "googlevideo.com",
                hostArgs = listOf(
                    "--split", "1",
                    "--disoob", "1",
                    "--oob", "25+s",
                    "--fake", "-1",
                    "--ttl", "4",
                    "--fake-sni", "www.google.com",
                ),
            ),
        ),
        DpiPreset(
            id = "hosts_yt_whitelist",
            title = "Whitelist YT hosts",
            description = "Только youtube/googleapis/googlevideo/ytimg",
            args = sock(
                "--hosts",
                ":googlevideo.com youtube.com youtubei.googleapis.com ytimg.com ggpht.com googlevideo.com",
                "--split", "1",
                "--disorder", "3+s",
                "--tlsrec", "1+s",
                "--fake", "-1",
                "--ttl", "3",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "multisplit_sni_ladder",
            title = "Лестница split по SNI",
            description = "Несколько split/disorder по смещениям SNI",
            args = sock(
                "--disorder", "1",
                "--disorder", "3+s",
                "--split", "6+s",
                "--disorder", "9+s",
                "--split", "12+s",
                "--disorder", "15+s",
                "--timeout", "3",
                "--auto=torst",
                "--tlsrec", "1+s",
            ),
        ),
        DpiPreset(
            id = "fake2_tlsrec_deep",
            title = "Fake-2 + deep tlsrec",
            description = "fake -2 и tlsrec 6+s / 27+s",
            args = sock(
                "--fake", "-2",
                "--disorder", "2",
                "--tlsrec", "6+s",
                "--tlsrec", "27+s",
                "--fake-sni", "www.google.com",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "drop_sack_fake",
            title = "Drop SACK + fake",
            description = "Linux drop-sack и fake",
            args = sock(
                "--drop-sack",
                "--fake", "-1",
                "--ttl", "5",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=torst",
                "--tlsrec", "1+s",
            ),
        ),
        DpiPreset(
            id = "proto_tls_oob",
            title = "TLS-only OOB",
            description = "Только TLS/HTTPS + oob в SNI",
            args = sock(
                "--proto", "tls,http",
                "--oob", "1",
                "--oob", "3+s",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=torst",
                "--fake", "-1",
                "--ttl", "6",
            ),
        ),
        DpiPreset(
            id = "s1_o1_At_chain",
            title = "s1/o1 auto-chain",
            description = "Цепочка -s1 -o1 -At -f-1 -r1+s",
            args = sock(
                "--split", "1",
                "--oob", "1",
                "--timeout", "3",
                "--auto=torst",
                "--fake", "-1",
                "--tlsrec", "1+s",
                "--auto=torst",
                "--disorder", "1",
                "--oob", "25+s",
            ),
        ),
        DpiPreset(
            id = "oob_multisplit",
            title = "OOB multi",
            description = "OOB + fake — часто тянет API",
            args = sock(
                "--oob", "1",
                "--oob", "3+s",
                "--timeout", "3",
                "--auto=torst",
                "--fake", "-1",
                "--ttl", "6",
                "--disorder", "1",
            ),
        ),
        DpiPreset(
            id = "fake_sni_google",
            title = "Fake SNI (Google)",
            description = "Фейковый ClientHello с SNI google + disorder",
            args = sock(
                "--fake", "-1",
                "--ttl", "6",
                "--fake-sni", "www.google.com",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=torst",
                "--tlsrec", "1+s",
            ),
        ),
        DpiPreset(
            id = "disorder_tlsrec",
            title = "Disorder + TLS record",
            description = "Классика ByeDPI: disorder и tlsrec по таймауту",
            args = sock(
                "--disorder", "1",
                "--timeout", "3",
                "--auto=torst",
                "--tlsrec", "1+s",
                "--fake", "-1",
                "--ttl", "8",
            ),
        ),
        DpiPreset(
            id = "split_oob",
            title = "Split + OOB",
            description = "Разбиение ClientHello и out-of-band байт",
            args = sock(
                "--split", "1",
                "--oob", "1",
                "--disorder", "3",
                "--timeout", "3",
                "--auto=torst",
                "--tlsrec", "1+s",
                "--fake", "-1",
                "--ttl", "6",
            ),
        ),
        DpiPreset(
            id = "mid_sni_split",
            title = "Split в SNI",
            description = "Разрез ClientHello внутри начала SNI",
            args = sock(
                "--split", "1+s",
                "--disorder", "3+s",
                "--timeout", "3",
                "--auto=torst",
                "--tlsrec", "1+s",
            ),
        ),
        DpiPreset(
            id = "split_hosts",
            title = "Разные стратегии по хостам",
            description = "googleapis мягко, googlevideo через oob 25+s + fake SNI",
            args = dualHost(
                defaultArgs = listOf(
                    "--oob", "1",
                    "--disorder", "1",
                    "--timeout", "3",
                    "--auto=torst",
                    "--fake", "-1",
                    "--ttl", "6",
                ),
                hosts = "googlevideo.com",
                hostArgs = listOf(
                    "--oob", "1",
                    "--oob", "25+s",
                    "--fake", "-1",
                    "--ttl", "5",
                    "--fake-sni", "www.google.com",
                    "--disorder", "1",
                ),
            ),
        ),
        DpiPreset(
            id = "oob_long_sni",
            title = "OOB для длинных SNI",
            description = "oob 25+s — для manifest.*.googlevideo.com",
            args = sock(
                "--oob", "1",
                "--oob", "25+s",
                "--timeout", "3",
                "--auto=torst",
                "--fake", "-1",
                "--ttl", "6",
                "--fake-sni", "www.google.com",
                "--disorder", "1",
            ),
        ),
        DpiPreset(
            id = "oob_tlsrec",
            title = "OOB + TLS record",
            description = "OOB с tlsrec",
            args = sock(
                "--oob", "1",
                "--oob", "3+s",
                "--timeout", "3",
                "--auto=torst",
                "--tlsrec", "1+s",
                "--tlsrec", "3+s",
                "--fake", "-1",
                "--ttl", "6",
            ),
        ),
        DpiPreset(
            id = "fake_only",
            title = "Только fake",
            description = "Минимум: fake-пакет с TTL и SNI google",
            args = sock(
                "--fake", "-1",
                "--ttl", "8",
                "--fake-sni", "www.google.com",
            ),
        ),
        DpiPreset(
            id = "disoob",
            title = "Disorder OOB",
            description = "disorder + disoob вокруг SNI",
            args = sock(
                "--disoob", "1",
                "--disorder", "3+s",
                "--timeout", "3",
                "--auto=torst",
                "--tlsrec", "1+s",
                "--fake", "-1",
                "--ttl", "6",
            ),
        ),
        DpiPreset(
            id = "aggressive_chain",
            title = "Агрессивная цепочка",
            description = "Несколько стратегий подряд с коротким таймаутом",
            args = sock(
                "--split", "1",
                "--disorder", "1",
                "--oob", "1",
                "--timeout", "2",
                "--auto=torst",
                "--tlsrec", "1+s",
                "--fake", "-1",
                "--ttl", "5",
                "--fake-sni", "www.google.com",
                "--split", "1+s",
            ),
        ),
        DpiPreset(
            id = "tlsrec_first",
            title = "TLS record first",
            description = "Сразу режем TLS record в SNI, без fake",
            args = sock(
                "--tlsrec", "1+s",
                "--tlsrec", "3+s",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=torst",
                "--split", "1",
            ),
        ),
        DpiPreset(
            id = "split_only",
            title = "Только split",
            description = "Минимальный split первого байта ClientHello",
            args = sock(
                "--split", "1",
                "--timeout", "3",
                "--auto=torst",
                "--disorder", "1",
                "--tlsrec", "1+s",
            ),
        ),
        DpiPreset(
            id = "fake_sni_cloudflare",
            title = "Fake SNI (Cloudflare)",
            description = "Фейковый SNI cloudflare.com + disorder",
            args = sock(
                "--fake", "-1",
                "--ttl", "5",
                "--fake-sni", "cloudflare.com",
                "--disorder", "1",
                "--timeout", "3",
                "--auto=torst",
                "--tlsrec", "1+s",
            ),
        ),
        DpiPreset(
            id = "oob_sni_only",
            title = "OOB в SNI",
            description = "OOB байт в области SNI",
            args = sock(
                "--oob", "2+s",
                "--timeout", "3",
                "--auto=torst",
                "--disorder", "1",
                "--tlsrec", "1+s",
                "--fake", "-1",
                "--ttl", "6",
            ),
        ),
        DpiPreset(
            id = "d1_s25s_d30s",
            title = "d1 + s25/d30",
            description = "СПб-2025 стиль: -d1 -s25+s -d30+s",
            args = sock(
                "--disorder", "1",
                "--split", "25+s",
                "--disorder", "30+s",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
        DpiPreset(
            id = "q1_r25s",
            title = "disoob + tlsrec 25+s",
            description = "-q1 -r25+s",
            args = sock(
                "--disoob", "1",
                "--tlsrec", "25+s",
                "--timeout", "3",
                "--auto=torst",
            ),
        ),
    )

    fun byId(id: String?): DpiPreset =
        ALL.firstOrNull { it.id == id } ?: ALL.first()
}
